/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param componentName 
 * @param currentApiVersion 
 * @param gitCommit 
 * @param node 
 * @param npmConfigUserAgent 
 * @param npmLifecycleEvent 
 * @param npmNodeExecpath 
 */


data class App (

    @Json(name = "component_name")
    val componentName: kotlin.String,

    @Json(name = "current_api_version")
    val currentApiVersion: kotlin.String,

    @Json(name = "git_commit")
    val gitCommit: kotlin.String,

    @Json(name = "node")
    val node: kotlin.String,

    @Json(name = "npm_config_user_agent")
    val npmConfigUserAgent: kotlin.String,

    @Json(name = "npm_lifecycle_event")
    val npmLifecycleEvent: kotlin.String,

    @Json(name = "npm_node_execpath")
    val npmNodeExecpath: kotlin.String

)

