/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param active 
 * @param env 
 * @param name 
 */


data class AppSignal (

    @Json(name = "active")
    val active: kotlin.String,

    @Json(name = "env")
    val env: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

)

