/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.DisplayClaimObject

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param display 
 * @param mandatory 
 */


data class ClaimObjectValue (

    @Json(name = "display")
    val display: kotlin.collections.List<DisplayClaimObject>? = null,

    @Json(name = "mandatory")
    val mandatory: kotlin.Boolean? = null

)

