/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param apiVersion 
 * @param gitCommit 
 * @param name 
 */


data class Component (

    @Json(name = "api_version")
    val apiVersion: kotlin.String,

    @Json(name = "git_commit")
    val gitCommit: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String

)

