/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.ClaimObjectValue
import me.meeco.holder.wallet.models.CredentialDefinition
import me.meeco.holder.wallet.models.CredentialDisplayObjectInner
import me.meeco.holder.wallet.models.IssuerDisplayObjectInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param claims 
 * @param credentialDefinition Object containing the detailed description of the credential type of the W3C VC Data Model.  Snapshot from Credential Issuer Metadata taken at the time of issuance. See Appendix A.1.1.2 in OpenID for Verifiable Credential Issuance for more information. 
 * @param did A DID managed by the wallet used to perform credential key binding.
 * @param display 
 * @param issuerDisplay 
 * @param kid An ID for a key managed by the wallet used to perform credential key binding.
 * @param vct The Credential type of the SD-JWT VC.  Snapshot from Credential Issuer Metadata taken at the time of issuance. See Appendix A.2.2 in OpenID for Verifiable Credential Issuance for more information. 
 */


data class CredentialResponseModelDtoMeta (

    @Json(name = "claims")
    val claims: kotlin.Any? = null,

    /* Object containing the detailed description of the credential type of the W3C VC Data Model.  Snapshot from Credential Issuer Metadata taken at the time of issuance. See Appendix A.1.1.2 in OpenID for Verifiable Credential Issuance for more information.  */
    @Json(name = "credential_definition")
    val credentialDefinition: CredentialDefinition? = null,

    /* A DID managed by the wallet used to perform credential key binding. */
    @Json(name = "did")
    val did: kotlin.String? = null,

    @Json(name = "display")
    val display: kotlin.collections.List<CredentialDisplayObjectInner>? = null,

    @Json(name = "issuer_display")
    val issuerDisplay: kotlin.collections.List<IssuerDisplayObjectInner>? = null,

    /* An ID for a key managed by the wallet used to perform credential key binding. */
    @Json(name = "kid")
    val kid: kotlin.String? = null,

    /* The Credential type of the SD-JWT VC.  Snapshot from Credential Issuer Metadata taken at the time of issuance. See Appendix A.2.2 in OpenID for Verifiable Credential Issuance for more information.  */
    @Json(name = "vct")
    val vct: kotlin.String? = null

)

