/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param state 
 * @param cNonce String containing a nonce to be used to create a proof of possession of key material when requesting a Credential
 * @param cNonceExpiresIn Number denoting the lifetime in seconds of the c_nonce.
 * @param credential Contains issued Credential. MUST be present when transaction_id is not returned. MAY be a string or an object, depending on the Credential format. See Appendix E for the Credential format specific encoding requirements.
 * @param credentialId Id under which the credential is stored in the wallet
 * @param transactionId A string identifying a Deferred Issuance transaction. This claim is contained in the response if the Credential Issuer was unable to immediately issue the Credential
 */


data class CredentialReceiveGetCredentialResponseModelDto (

    @Json(name = "state")
    val state: kotlin.String,

    /* String containing a nonce to be used to create a proof of possession of key material when requesting a Credential */
    @Json(name = "c_nonce")
    val cNonce: kotlin.String? = null,

    /* Number denoting the lifetime in seconds of the c_nonce. */
    @Json(name = "c_nonce_expires_in")
    val cNonceExpiresIn: kotlin.Int? = null,

    /* Contains issued Credential. MUST be present when transaction_id is not returned. MAY be a string or an object, depending on the Credential format. See Appendix E for the Credential format specific encoding requirements. */
    @Json(name = "credential")
    val credential: kotlin.String? = null,

    /* Id under which the credential is stored in the wallet */
    @Json(name = "credential_id")
    val credentialId: kotlin.String? = null,

    /* A string identifying a Deferred Issuance transaction. This claim is contained in the response if the Credential Issuer was unable to immediately issue the Credential */
    @Json(name = "transaction_id")
    val transactionId: kotlin.String? = null

)

