/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error 
 * @param extraInfo 
 * @param message 
 */


data class CredentialVerificationCheckModelDto (

    @Json(name = "error")
    val error: kotlin.String,

    @Json(name = "extra_info")
    val extraInfo: kotlin.Any,

    @Json(name = "message")
    val message: kotlin.String

)

