/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Additional information about the credential to be imported.
 *
 * @param did A DID managed by the wallet used to perform credential key binding.
 * @param kid An ID for a key managed by the wallet used to perform credential key binding.
 */


data class CredentialImportRequestModelDtoMeta (

    /* A DID managed by the wallet used to perform credential key binding. */
    @Json(name = "did")
    val did: kotlin.String? = null,

    /* An ID for a key managed by the wallet used to perform credential key binding. */
    @Json(name = "kid")
    val kid: kotlin.String? = null

)

