/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Array designating the types a certain Credential type supports, according to VC Data Model, Section 4.3.
 * @param credentialSubject Object containing a list of name/value pairs, where each name identifies a claim offered in the Credential.
 */


data class CredentialDefinition (

    /* Array designating the types a certain Credential type supports, according to VC Data Model, Section 4.3. */
    @Json(name = "type")
    val type: kotlin.collections.List<kotlin.String>,

    /* Object containing a list of name/value pairs, where each name identifies a claim offered in the Credential. */
    @Json(name = "credentialSubject")
    val credentialSubject: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

