/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.CredentialReceiveStateModelDto
import me.meeco.holder.wallet.models.Meta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param states 
 * @param meta 
 */


data class CredentialReceiveStatesModelDto (

    @Json(name = "states")
    val states: kotlin.collections.List<CredentialReceiveStateModelDto>,

    @Json(name = "meta")
    val meta: Meta

)

