/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param proofType 
 * @param jwt Compact JWT of proof JWT used to issue the credential
 */


data class CredentialReceiveStateModelDtoProof (

    @Json(name = "proof_type")
    val proofType: kotlin.String? = null,

    /* Compact JWT of proof JWT used to issue the credential */
    @Json(name = "jwt")
    val jwt: kotlin.String? = null

)

