/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 */


data class CredentialReceiveGetAccessTokenRequestModelDtoAuthorizationDetailsInnerCredentialDefinitionOneOf1 (

    @Json(name = "type")
    val type: kotlin.collections.List<kotlin.String>? = null

)

