/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.GrantDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param credentialIssuer 
 * @param credentials 
 * @param grants 
 */


data class CredentialOfferDto (

    @Json(name = "credential_issuer")
    val credentialIssuer: kotlin.String? = null,

    @Json(name = "credentials")
    val credentials: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "grants")
    val grants: GrantDto? = null

)

