/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.CredentialReceiveGetAccessTokenRequestModelDtoAuthorizationDetailsInnerCredentialDefinition

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param format 
 * @param type 
 * @param credentialDefinition 
 */


data class CredentialReceiveGetAccessTokenRequestModelDtoAuthorizationDetailsInner (

    @Json(name = "format")
    val format: CredentialReceiveGetAccessTokenRequestModelDtoAuthorizationDetailsInner.Format,

    @Json(name = "type")
    val type: CredentialReceiveGetAccessTokenRequestModelDtoAuthorizationDetailsInner.Type,

    @Json(name = "credential_definition")
    val credentialDefinition: CredentialReceiveGetAccessTokenRequestModelDtoAuthorizationDetailsInnerCredentialDefinition? = null

) {

    /**
     * 
     *
     * Values: vcPlusSdMinusJwt,jwtVcJson
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "vc+sd-jwt") vcPlusSdMinusJwt("vc+sd-jwt"),
        @Json(name = "jwt_vc_json") jwtVcJson("jwt_vc_json");
    }
    /**
     * 
     *
     * Values: openidCredential
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "openid_credential") openidCredential("openid_credential");
    }
}

