/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.CredentialResponseModelDtoMeta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param credential The encoded string representation of the credential.
 * @param format Format of the credential.
 * @param id A unique identifier of the credential.
 * @param createdAt The date and time when the credential was added to a Wallet.
 * @param meta 
 */


data class CredentialResponseModelDto (

    /* The encoded string representation of the credential. */
    @Json(name = "credential")
    val credential: kotlin.String,

    /* Format of the credential. */
    @Json(name = "format")
    val format: CredentialResponseModelDto.Format,

    /* A unique identifier of the credential. */
    @Json(name = "id")
    val id: kotlin.String,

    /* The date and time when the credential was added to a Wallet. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "meta")
    val meta: CredentialResponseModelDtoMeta? = null

) {

    /**
     * Format of the credential.
     *
     * Values: vcPlusSdMinusJwt,jwtVcJson
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "vc+sd-jwt") vcPlusSdMinusJwt("vc+sd-jwt"),
        @Json(name = "jwt_vc_json") jwtVcJson("jwt_vc_json");
    }
}

