/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.CredentialVerificationCheckModelDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param checks 
 * @param errors 
 * @param id 
 * @param warnings 
 */


data class CredentialVerificationResponseDto (

    @Json(name = "checks")
    val checks: kotlin.collections.List<CredentialVerificationResponseDto.Checks>,

    @Json(name = "errors")
    val errors: kotlin.collections.List<CredentialVerificationCheckModelDto>,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "warnings")
    val warnings: kotlin.Any?

) {

    /**
     * 
     *
     * Values: format,signature,expiration,nonce,schema,revocationStatus
     */
    @JsonClass(generateAdapter = false)
    enum class Checks(val value: kotlin.String) {
        @Json(name = "format") format("format"),
        @Json(name = "signature") signature("signature"),
        @Json(name = "expiration") expiration("expiration"),
        @Json(name = "nonce") nonce("nonce"),
        @Json(name = "schema") schema("schema"),
        @Json(name = "revocation_status") revocationStatus("revocation_status");
    }
}

