/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.CredentialImportRequestModelDtoMeta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param credential The encoded string representation of the credential to be imported.
 * @param meta 
 */


data class CredentialImportRequestModelDto (

    /* The encoded string representation of the credential to be imported. */
    @Json(name = "credential")
    val credential: kotlin.String,

    @Json(name = "meta")
    val meta: CredentialImportRequestModelDtoMeta? = null

)

