/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param host 
 * @param name 
 * @param port 
 * @param user 
 */


data class Database (

    @Json(name = "host")
    val host: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "port")
    val port: kotlin.String,

    @Json(name = "user")
    val user: kotlin.String

)

