/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.DidControllerCreateRequestOptionsKey

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param codec 
 * @param key 
 * @param network 
 */


data class DidControllerCreateRequestOptions (

    @Json(name = "codec")
    val codec: kotlin.String? = null,

    @Json(name = "key")
    val key: DidControllerCreateRequestOptionsKey? = null,

    @Json(name = "network")
    val network: kotlin.String? = null

)

