/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.DidControllerCreateRequestOptions

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param method 
 * @param options 
 */


data class DidControllerCreateRequest (

    @Json(name = "method")
    val method: kotlin.String? = null,

    @Json(name = "options")
    val options: DidControllerCreateRequestOptions? = null

)

