/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param inputMode 
 * @param length 
 * @param description 
 */


data class GrantDtoUrnIetfParamsOauthGrantTypePreAuthorizedCodeTxCode (

    @Json(name = "input_mode")
    val inputMode: GrantDtoUrnIetfParamsOauthGrantTypePreAuthorizedCodeTxCode.InputMode? = null,

    @Json(name = "length")
    val length: java.math.BigDecimal? = null,

    @Json(name = "description")
    val description: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: numeric,text
     */
    @JsonClass(generateAdapter = false)
    enum class InputMode(val value: kotlin.String) {
        @Json(name = "numeric") numeric("numeric"),
        @Json(name = "text") text("text");
    }
}

