/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.GrantDtoAuthorizationCode
import me.meeco.holder.wallet.models.GrantDtoUrnIetfParamsOauthGrantTypePreAuthorizedCode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param authorizationCode 
 * @param urnColonIetfColonParamsColonOauthColonGrantTypeColonPreAuthorizedCode 
 */


data class GrantDto (

    @Json(name = "authorization_code")
    val authorizationCode: GrantDtoAuthorizationCode? = null,

    @Json(name = "urn:ietf:params:oauth:grant-type:pre-authorized_code")
    val urnColonIetfColonParamsColonOauthColonGrantTypeColonPreAuthorizedCode: GrantDtoUrnIetfParamsOauthGrantTypePreAuthorizedCode? = null

)

