/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.GrantDtoUrnIetfParamsOauthGrantTypePreAuthorizedCodeTxCode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param preAuthorizedCode 
 * @param txCode 
 */


data class GrantDtoUrnIetfParamsOauthGrantTypePreAuthorizedCode (

    @Json(name = "pre_authorized_code")
    val preAuthorizedCode: kotlin.String? = null,

    @Json(name = "tx_code")
    val txCode: GrantDtoUrnIetfParamsOauthGrantTypePreAuthorizedCodeTxCode? = null

)

