/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fields 
 * @param limitDisclosure 
 */


data class InputDescriptorConstraints (

    @Json(name = "fields")
    val fields: kotlin.Any? = null,

    @Json(name = "limit_disclosure")
    val limitDisclosure: InputDescriptorConstraints.LimitDisclosure? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * 
     *
     * Values: required,preferred
     */
    @JsonClass(generateAdapter = false)
    enum class LimitDisclosure(val value: kotlin.Any) {
        @Json(name = "required") required("required"),
        @Json(name = "preferred") preferred("preferred");
    }
}

