/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param alg 
 * @param crv 
 * @param e 
 * @param k 
 * @param kid 
 * @param kty 
 * @param n 
 * @param x 
 * @param y 
 */


data class JSONWebKeyPub (

    @Json(name = "alg")
    val alg: kotlin.String? = null,

    @Json(name = "crv")
    val crv: kotlin.String? = null,

    @Json(name = "e")
    val e: kotlin.String? = null,

    @Json(name = "k")
    val k: kotlin.String? = null,

    @Json(name = "kid")
    val kid: kotlin.String? = null,

    @Json(name = "kty")
    val kty: kotlin.String? = null,

    @Json(name = "n")
    val n: kotlin.String? = null,

    @Json(name = "x")
    val x: kotlin.String? = null,

    @Json(name = "y")
    val y: kotlin.String? = null

)

