/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param crv 
 * @param d 
 * @param dp 
 * @param dq 
 * @param e 
 * @param k 
 * @param kid 
 * @param kty 
 * @param n 
 * @param p 
 * @param q 
 * @param qi 
 * @param x 
 * @param y 
 */


data class JSONWebKey (

    @Json(name = "crv")
    val crv: kotlin.String? = null,

    @Json(name = "d")
    val d: kotlin.String? = null,

    @Json(name = "dp")
    val dp: kotlin.String? = null,

    @Json(name = "dq")
    val dq: kotlin.String? = null,

    @Json(name = "e")
    val e: kotlin.String? = null,

    @Json(name = "k")
    val k: kotlin.String? = null,

    @Json(name = "kid")
    val kid: kotlin.String? = null,

    @Json(name = "kty")
    val kty: kotlin.String? = null,

    @Json(name = "n")
    val n: kotlin.String? = null,

    @Json(name = "p")
    val p: kotlin.String? = null,

    @Json(name = "q")
    val q: kotlin.String? = null,

    @Json(name = "qi")
    val qi: kotlin.String? = null,

    @Json(name = "x")
    val x: kotlin.String? = null,

    @Json(name = "y")
    val y: kotlin.String? = null

)

