/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param orderBy 
 * @param order 
 * @param orderFromParams 
 * @param perPage 
 * @param perPageFromParams 
 * @param recordsCount 
 * @param page 
 * @param pageCount 
 */


data class Meta (

    @Json(name = "order_by")
    val orderBy: kotlin.String,

    @Json(name = "order")
    val order: Meta.Order,

    @Json(name = "order_from_params")
    val orderFromParams: kotlin.Boolean,

    @Json(name = "per_page")
    val perPage: java.math.BigDecimal,

    @Json(name = "per_page_from_params")
    val perPageFromParams: kotlin.Boolean,

    @Json(name = "records_count")
    val recordsCount: java.math.BigDecimal,

    @Json(name = "page")
    val page: java.math.BigDecimal,

    @Json(name = "page_count")
    val pageCount: java.math.BigDecimal

) {

    /**
     * 
     *
     * Values: aSC,dESC
     */
    @JsonClass(generateAdapter = false)
    enum class Order(val value: kotlin.String) {
        @Json(name = "ASC") aSC("ASC"),
        @Json(name = "DESC") dESC("DESC");
    }
}

