/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.PresentationRequestSetCredentialsRequestModelDtoCredentialsInnerCredential

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param credential 
 * @param inputDescriptorId 
 */


data class PresentationRequestSetCredentialsRequestModelDtoCredentialsInner (

    @Json(name = "credential")
    val credential: PresentationRequestSetCredentialsRequestModelDtoCredentialsInnerCredential,

    @Json(name = "input_descriptor_id")
    val inputDescriptorId: kotlin.String

)

