/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.Meta
import me.meeco.holder.wallet.models.PresentationStateResponseDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param presentationStates 
 * @param meta 
 */


data class PresentationStatesResponseDto (

    @Json(name = "presentation_states")
    val presentationStates: kotlin.collections.List<PresentationStateResponseDto>,

    @Json(name = "meta")
    val meta: Meta

)

