/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.PresentationRequestSetCredentialsRequestModelDtoCredentialsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param credentials 
 * @param state 
 */


data class PresentationRequestSetCredentialsRequestModelDto (

    @Json(name = "credentials")
    val credentials: kotlin.collections.List<PresentationRequestSetCredentialsRequestModelDtoCredentialsInner>,

    @Json(name = "state")
    val state: kotlin.String

)

