/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.PresentationRequestSetCredentialsResponseModelDtoMeta

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param meta 
 * @param redirectUri Redirect URI to follow on the frontend.  In case of response_mode `fragment`, this contains the Authorization Response attributes and this is how they are passed to the verifier.  In case of response_mode `direct_post`, this is the URI that was returned after successfully posting the Authorization Response to the `response_uri` of the verifier. 
 * @param state 
 */


data class PresentationRequestSubmitResponseModelDto (

    @Json(name = "meta")
    val meta: PresentationRequestSetCredentialsResponseModelDtoMeta? = null,

    /* Redirect URI to follow on the frontend.  In case of response_mode `fragment`, this contains the Authorization Response attributes and this is how they are passed to the verifier.  In case of response_mode `direct_post`, this is the URI that was returned after successfully posting the Authorization Response to the `response_uri` of the verifier.  */
    @Json(name = "redirect_uri")
    val redirectUri: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null

)

