/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param authorizationRequestUri 
 * @param protocolVersion Specification draft version presentation request uses. If not specified draft10 is used.
 */


data class PresentationRequestSendRequestModelDto (

    @Json(name = "authorization_request_uri")
    val authorizationRequestUri: kotlin.String,

    /* Specification draft version presentation request uses. If not specified draft10 is used. */
    @Json(name = "protocol_version")
    val protocolVersion: PresentationRequestSendRequestModelDto.ProtocolVersion? = null

) {

    /**
     * Specification draft version presentation request uses. If not specified draft10 is used.
     *
     * Values: draft10,draft18
     */
    @JsonClass(generateAdapter = false)
    enum class ProtocolVersion(val value: kotlin.String) {
        @Json(name = "draft10") draft10("draft10"),
        @Json(name = "draft18") draft18("draft18");
    }
}

