/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.InputDescriptor
import me.meeco.holder.wallet.models.SubmissionRequirement

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param inputDescriptors 
 * @param submissionRequirements 
 */


data class PresentationDefinition (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "input_descriptors")
    val inputDescriptors: kotlin.collections.List<InputDescriptor>,

    @Json(name = "submission_requirements")
    val submissionRequirements: kotlin.collections.List<SubmissionRequirement>? = null

)

