/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param host 
 * @param port 
 * @param db 
 * @param tlsEnabled 
 */


data class Redis (

    @Json(name = "host")
    val host: kotlin.String,

    @Json(name = "port")
    val port: kotlin.String,

    @Json(name = "db")
    val db: kotlin.String,

    @Json(name = "tlsEnabled")
    val tlsEnabled: kotlin.Boolean

)

