/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.App
import me.meeco.holder.wallet.models.AppSignal
import me.meeco.holder.wallet.models.Database
import me.meeco.holder.wallet.models.HealthCheck
import me.meeco.holder.wallet.models.Redis

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param app 
 * @param appsignal 
 * @param database 
 * @param redis 
 * @param healthCheck 
 */


data class StatusDto (

    @Json(name = "app")
    val app: App,

    @Json(name = "appsignal")
    val appsignal: AppSignal,

    @Json(name = "database")
    val database: Database,

    @Json(name = "redis")
    val redis: Redis,

    @Json(name = "healthCheck")
    val healthCheck: HealthCheck

)

