/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.SubmissionRequirementOneOf

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param from 
 * @param rule 
 * @param count 
 * @param name 
 */


data class SubmissionRequirement (

    @Json(name = "from")
    val from: kotlin.Any?,

    @Json(name = "rule")
    val rule: SubmissionRequirement.Rule?,

    @Json(name = "count")
    val count: kotlin.Any? = null,

    @Json(name = "name")
    val name: kotlin.Any? = null

) {

    /**
     * 
     *
     * Values: pick
     */
    @JsonClass(generateAdapter = false)
    enum class Rule(val value: kotlin.Any) {
        @Json(name = "pick") pick("pick");
    }
}

