/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.WalletDIDDtoKeysInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param propertyKeys 
 */


data class WalletDIDDto (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "keys")
    val propertyKeys: kotlin.collections.List<WalletDIDDtoKeysInner>? = null

)

