/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.meeco.holder.wallet.models

import me.meeco.holder.wallet.models.JSONWebKeyPub
import me.meeco.holder.wallet.models.WalletDIDDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dids 
 * @param externalReference 
 * @param id 
 * @param propertyKeys 
 */


data class WalletResponseModelDto (

    @Json(name = "dids")
    val dids: kotlin.collections.List<WalletDIDDto>,

    @Json(name = "external_reference")
    val externalReference: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "keys")
    val propertyKeys: kotlin.collections.List<JSONWebKeyPub>

)

